// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtazyqdkbjorltcfxckw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0YXp5cWRrYmpvcmx0Y2Z4Y2t3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MjYwMjgsImV4cCI6MjA3ODIwMjAyOH0.k33cSZZruSxw384rT6vB9ZI6sFIk7V36oPG3S8cjz-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});